version: "3.8"

services:

  mpd:
    image: blaxpot/mpd
    ports:
      - "6600:6600"
      - "8800:8800"
    volumes:
      - ./data/music:/music
      - ./data/mpd:/var/lib/mpd
    restart: unless-stopped
    command: "100"
